


--TRIGGERS...
--$$ ....$$ DELIMETERS USED LIKE I WANT SELECT 'I'M STUDENT' I GET ERROR DUE TO APOSTROPHE SO
--EITHER I CAN USE SELECT E'I\'M STDUENT' OR USE DELIMETER ...SELECT $$ 'I'M STUDENT' $$
--IN POSTGRE WE ONLY USE $$ BUT FOR OTHER SQL LANGUAGES WE CAN USE @,// ANYTHI

CREATE TABLE EMPLYE(EMP_ID INT,EMP_NAME VARCHAR(10),DEPT_ID INT,SALARY INT, MANAGER_ID INT);
CREATE TABLE DEPARTMENT(DEPT_ID INT,DEPT_NAME VARCHAR(10),BUDGET INT);
CREATE TABLE PROJECT (PROJECT_ID INT,PROJECT_NAME VARCHAR(10),DEPT_ID INT,COST_ INT);
CREATE TABLE TIMESHEET(EMP_ID INT,PROJECT_ID INT,HOURS_LOGGED INT);

INSERT INTO EMPLYE(EMP_ID,EMP_NAME,DEPT_ID,SALARY,MANAGER_ID) VALUES (1,'ALICE',10,90000,3);
INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME,BUDGET) VALUES(10,'IT',80000);
INSERT INTO PROJECT(PROJECT_ID,PROJECT_NAME,DEPT_ID,COST_ ) VALUES (101,'PORTAL',10,95000);
INSERT INTO TIMESHEET(EMP_ID,PROJECT_ID,HOURS_LOGGED) VALUES (1,101,20);

SELECT 
    e.EMP_ID,
    e.EMP_NAME,
    p.PROJECT_NAME,
    t.HOURS_LOGGED
FROM EMPLYE e
JOIN TIMESHEET t ON e.EMP_ID = t.EMP_ID
JOIN PROJECT p ON t.PROJECT_ID = p.PROJECT_ID
WHERE t.HOURS_LOGGED >
      (
        SELECT AVG(t2.HOURS_LOGGED)
        FROM TIMESHEET t2
        JOIN PROJECT p2 ON t2.PROJECT_ID = p2.PROJECT_ID
        WHERE p2.DEPT_ID = e.DEPT_ID
      );
