--EXPERIMENT 2--
--MEDIUM PROBLEM--

CREATE TABLE EMPLOYEE(
EMPID INT PRIMARY KEY IDENTITY(1,1),ENAME VARCHAR(MAX),DEPARTMENT VARCHAR(MAX),MANAGERID INT,
FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEE(EMPID));

INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,MANAGERID) VALUES ('ALICE','HR',NULL)
INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,MANAGERID) VALUES ('BOB','FINANCE',1)
INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,MANAGERID) VALUES ('CHARLIE','IT',1)
INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,MANAGERID) VALUES ('DAVID','FINANCE',2)
INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,MANAGERID) VALUES ('EVE','IT',3)
INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,MANAGERID) VALUES ('FRANK','HR',1)
SELECT * FROM EMPLOYEE;

SELECT M.ENAME AS [EMPLOYEE NAME],M.DEPARTMENT AS [EMPLOYEE DEPARTMENT],E.ENAME AS [MANAGER NAME],E.DEPARTMENT AS [MANAGERDEPT]
FROM EMPLOYEE AS E
RIGHT OUTER JOIN
EMPLOYEE AS M
ON E.EMPID=M.MANAGERID





--EXPERIMENT 2--
--HARD PROBLEM--

-- Create Year_tbl (holds actual NPV values)
CREATE TABLE YEAR_TBL (
    ID INT,
    YEAR INT,
    NPV INT
);

-- Create Queries table (requested values)
CREATE TABLE QUERIES_TBL (
    ID INT,
    YEAR INT
);

-- Insert data into Year_tbl
INSERT INTO YEAR_TBL (ID, YEAR, NPV)
VALUES
(1, 2018, 100),
(7, 2020, 30),
(13, 2019, 40),
(1, 2019, 113),
(2, 2008, 121),
(3, 2009, 12),
(11, 2020, 99),
(7, 2019, 0);

-- Insert data into Queries
INSERT INTO QUERIES_TBL (ID, YEAR)
VALUES
(1, 2019),
(2, 2008),
(3, 2009),
(7, 2018),
(7, 2019),
(7, 2020),
(13, 2019);

SELECT * FROM YEAR_TBL;
SELECT * FROM QUERIES_TBL;

SELECT Q.ID AS [ID],Q.YEAR AS [YEAR],ISNULL(NPV,0) AS [NPV]
FROM QUERIES_TBL AS Q
LEFT OUTER JOIN
YEAR_TBL AS Y
ON Q.ID=Y.ID AND Q.YEAR=Y.YEAR